version: "3.9"
services:
  database:
    image: mongo
    restart: on-failure
    container_name: contacts_database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - ./data:/data/db
  application:
    build: ..
    restart: on-failure
    container_name: contacts_application
    depends_on:
      - database
    ports:
      - "3000:3000"
  proxy:
    image: nginx
    restart: on-failure
    container_name: contacts_proxy
    volumes:
    - ./nginx:/etc/nginx/templates
    ports:
    - "8080:80"
    depends_on:
      - application
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
