// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

// Injectors from injection.go:

func GetInjection() Injection {
	mongoDataSource := NewMongoDataSource()
	contactRepository := NewContactRepositoryMongo(mongoDataSource)
	injection := NewInjection(mongoDataSource, contactRepository)
	return injection
}

// injection.go:

type Injection struct {
	DataSource        MongoDataSource
	ContactRepository ContactRepository
}

func NewInjection(datasource MongoDataSource, repository ContactRepository) Injection {
	return Injection{
		DataSource:        datasource,
		ContactRepository: repository,
	}
}
